elinks: upstream upgrade to 0.11.1 and package cleanup

diff --git a/sources/elinks/configure.patch b/sources/elinks/configure.patch
--- a/sources/elinks/configure.patch
+++ b/sources/elinks/configure.patch
@@ -1,19 +1,32 @@
---- elinks/configure.orig	2005-01-25 11:04:05.000000000 -0800
-+++ elinks/configure	2005-01-25 11:07:35.000000000 -0800
-@@ -1131,16 +1131,12 @@
- if eval "test \"`echo '$''{'ac_cv_file_$ac_safe'+set}'`\" = set"; then
-   echo $ac_n "(cached) $ac_c" 1>&6
+--- elinks-0.11.1/configure	2006-01-29 14:10:47.000000000 +0100
++++ elinks/configure	2006-07-20 21:45:47.000000000 +0200
+@@ -1578,10 +1578,10 @@
+ if eval "test \"\${$as_ac_File+set}\" = set"; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
  else
--  if test "$cross_compiling" = yes; then
--    { echo "configure: error: Cannot check for file existence when cross compiling" 1>&2; exit 1; }
--else
-   if test -r "$features"; then
-     eval "ac_cv_file_$ac_safe=yes"
-   else
-     eval "ac_cv_file_$ac_safe=no"
-   fi
- fi
--fi
- if eval "test \"`echo '$ac_cv_file_'$ac_safe`\" = yes"; then
-   echo "$ac_t""yes" 1>&6
-    . $features 
+-  test "$cross_compiling" = yes &&
+-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+-   { (exit 1); exit 1; }; }
++#  test "$cross_compiling" = yes &&
++#  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
++#echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
++#   { (exit 1); exit 1; }; }
+ if test -r ""$srcdir/$features""; then
+   eval "$as_ac_File=yes"
+ else
+@@ -1600,10 +1600,10 @@
+ if eval "test \"\${$as_ac_File+set}\" = set"; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
+-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+-   { (exit 1); exit 1; }; }
++#  test "$cross_compiling" = yes &&
++#  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
++#echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
++#   { (exit 1); exit 1; }; }
+ if test -r ""$builddir/$features""; then
+   eval "$as_ac_File=yes"
+ else
