minihttpd: wrapper startup bugfixes

diff --git a/trunk/sources/minihttpd/scripts.patch b/trunk/sources/minihttpd/scripts.patch
--- a/trunk/sources/minihttpd/scripts.patch
+++ b/trunk/sources/minihttpd/scripts.patch
@@ -1,13 +1,13 @@
-diff -urN mini_httpd-1.19/scripts/mini_httpd.sh minihttpd/scripts/mini_httpd.sh
 --- mini_httpd-1.19/scripts/mini_httpd.sh	2001-12-28 23:14:33.000000000 +0100
-+++ minihttpd/scripts/mini_httpd.sh	2006-02-09 14:21:06.000000000 +0100
-@@ -1,20 +1,20 @@
++++ minihttpd/scripts/mini_httpd.sh	2006-02-16 10:25:41.000000000 +0100
+@@ -1,24 +1,31 @@
  #!/bin/sh
  #
 -# mini_httpd.sh - startup script for mini_httpd on FreeBSD
 +# mini_httpd.sh - startup script for mini_httpd on Optware
  #
- # This goes in /usr/local/etc/rc.d and gets run at boot-time.
+-# This goes in /usr/local/etc/rc.d and gets run at boot-time.
++# This goes in /opt/etc/init.d and gets run at boot-time.
  
  case "$1" in
   
@@ -17,18 +17,29 @@ diff -urN mini_httpd-1.19/scripts/mini_httpd.sh minihttpd/scripts/mini_httpd.sh
  	echo -n " mini_httpd"
 -	/usr/local/sbin/mini_httpd_wrapper &
 +	/opt/sbin/mini_httpd_wrapper &
++	echo "$!" > /opt/var/run/mini_httpd_wrapper.pid
      fi
      ;;
  
      stop)
 -    kill -USR1 `cat /var/run/mini_httpd.pid`
++    kill `cat /opt/var/run/mini_httpd_wrapper.pid`
 +    kill -USR1 `cat /opt/var/run/mini_httpd.pid`
      ;;
++    
++    restart)
++    kill -USR1 `cat /opt/var/run/mini_httpd.pid` 
++    ;;
++    
  	    
      *)
-diff -urN mini_httpd-1.19/scripts/mini_httpd_wrapper minihttpd/scripts/mini_httpd_wrapper
+-    echo "usage: $0 { start | stop }" >&2
++    echo "usage: $0 { start | stop | restart}" >&2
+     exit 1
+     ;;
+ 			     
 --- mini_httpd-1.19/scripts/mini_httpd_wrapper	2002-06-19 16:13:21.000000000 +0200
-+++ minihttpd/scripts/mini_httpd_wrapper	2006-02-09 14:23:29.000000000 +0100
++++ minihttpd/scripts/mini_httpd_wrapper	2006-02-16 10:27:05.000000000 +0100
 @@ -1,8 +1,8 @@
  #!/bin/sh
  #
@@ -40,13 +51,14 @@ diff -urN mini_httpd-1.19/scripts/mini_httpd_wrapper minihttpd/scripts/mini_http
  # exits then the script restarts it automatically.
  #
  # The -D flag tells mini_httpd to *not* put itself into the background,
-@@ -10,12 +10,9 @@
+@@ -10,12 +10,10 @@
  # the specified config file.
  
  while true ; do
 -    /usr/local/sbin/mini_httpd -D -C /usr/local/www/mini_httpd_config
 -    if [ -f /var/run/nologin ] ; then
 +    /opt/sbin/mini_httpd -D -C /opt/etc/mini_httpd.conf
++    logger "mini_httpd "estarted due to error #$?"
 +    if [ -f /opt/var/run/nologin ] ; then
  	exit
      fi
