Change workflow to allow targets with prefix other then /opt Prefix is defined by TARGET_PREFIX variable. It defaults to /opt and should be overriden in platforms/toolchain-$(OPTWARE_TARGET).mk
Source files (scripts, configs and patches) now must use '%OPTWARE_TARGET_PREFIX%' instead of hardcoded '/opt'. $(INSTALL) and $(PATCH) are now used (instead of 'install' and 'patch' commands) to replace this keyword with actual target prefix: see scripts/install.sh and scripts/patch.sh

This major change has been accomplished with the use of complex regular expressions. Further testing is needed

diff --git a/sources/eggdrop/postinst b/sources/eggdrop/postinst
--- a/sources/eggdrop/postinst
+++ b/sources/eggdrop/postinst
@@ -1,10 +1,10 @@
 #!/bin/sh
 
-PATH=/sbin:/bin:/usr/bin:/usr/sbin:/opt/bin:/opt/sbin
+PATH=/sbin:/bin:/usr/bin:/usr/sbin:%OPTWARE_TARGET_PREFIX%/bin:%OPTWARE_TARGET_PREFIX%/sbin
 
 print_conf_info () {
 	echo ; echo
-	echo "A template configuration file is installed here : /opt/etc/eggdrop.conf"
+	echo "A template configuration file is installed here : %OPTWARE_TARGET_PREFIX%/etc/eggdrop.conf"
 	echo "Please read the eggdrop documentation to create a configuration file matching your needs."
 	echo
 }
@@ -18,10 +18,10 @@ if grep -q ^eggdrop: /etc/passwd; then
 	echo There already is an eggdrop user on the system.
 else
 	echo -n "No eggdrop user found, creating it... "
-	adduser -S -h /opt/share/eggdrop -g "eggdrop daemon" -s /bin/false -D -H  $ADDUSER_OPT eggdrop > /dev/null 2>&1 || (echo "Warning! Failed to create eggdrop user/group"; print_conf_info; exit 0)
+	adduser -S -h %OPTWARE_TARGET_PREFIX%/share/eggdrop -g "eggdrop daemon" -s /bin/false -D -H  $ADDUSER_OPT eggdrop > /dev/null 2>&1 || (echo "Warning! Failed to create eggdrop user/group"; print_conf_info; exit 0)
 	echo done
 fi
-chown -R eggdrop.eggdrop /opt/share/eggdrop
-chmod 700 /opt/share/eggdrop
+chown -R eggdrop.eggdrop %OPTWARE_TARGET_PREFIX%/share/eggdrop
+chmod 700 %OPTWARE_TARGET_PREFIX%/share/eggdrop
 
 print_conf_info
