eggdrop: 1.6.19 -> 1.6.21; fix GCC 5+ build and scripts

diff --git a/sources/eggdrop/postinst b/sources/eggdrop/postinst
--- a/sources/eggdrop/postinst
+++ b/sources/eggdrop/postinst
@@ -2,6 +2,13 @@
 
 PATH=/sbin:/bin:/usr/bin:/usr/sbin:/opt/bin:/opt/sbin
 
+print_conf_info () {
+	echo ; echo
+	echo "A template configuration file is installed here : /opt/etc/eggdrop.conf"
+	echo "Please read the eggdrop documentation to create a configuration file matching your needs."
+	echo
+}
+
 if grep -q ^eggdrop: /etc/group; then
 	echo There already is an eggdrop group on the system.
 	ADDUSER_OPT="-G eggdrop"
@@ -11,14 +18,10 @@ if grep -q ^eggdrop: /etc/passwd; then
 	echo There already is an eggdrop user on the system.
 else
 	echo -n "No eggdrop user found, creating it... "
-	adduser -S -h /opt/share/eggdrop -g "eggdrop daemon" -s /bin/false -D -H  $ADDUSER_OPT eggdrop > /dev/null 2>&1
+	adduser -S -h /opt/share/eggdrop -g "eggdrop daemon" -s /bin/false -D -H  $ADDUSER_OPT eggdrop > /dev/null 2>&1 || (echo "Warning! Failed to create eggdrop user/group"; print_conf_info; exit 0)
 	echo done
 fi
 chown -R eggdrop.eggdrop /opt/share/eggdrop
 chmod 700 /opt/share/eggdrop
 
-echo ; echo
-echo "A template configuration file is installed here : /opt/etc/eggdrop.conf"
-echo "Please read the eggdrop documentation to create a configuration file matching you needs."
-echo
-
+print_conf_info
