smartmontools: upstream to 5.36

diff --git a/sources/smartmontools/configure.patch b/sources/smartmontools/configure.patch
--- a/sources/smartmontools/configure.patch
+++ b/sources/smartmontools/configure.patch
@@ -1,17 +1,17 @@
---- configure	2004-09-10 06:11:46.000000000 +0200
-+++ configure.patched	2005-09-11 13:27:13.000000000 +0200
-@@ -2166,11 +2166,11 @@
-   echo "$as_me: failed program was:" >&5
- sed 's/^/| /' conftest.$ac_ext >&5
- 
--{ { echo "$as_me:$LINENO: error: C compiler cannot create executables
-+{ { echo "$as_me:$LINENO: warning: C compiler cannot create executables
+--- configure.old	2006-06-19 16:38:35.000000000 +1000
++++ configure	2006-06-19 16:40:27.000000000 +1000
+@@ -6443,11 +6443,11 @@
+ echo "$as_me:$LINENO: checking for working snprintf" >&5
+ echo $ECHO_N "checking for working snprintf... $ECHO_C" >&6
+ if test "$cross_compiling" = yes; then
+-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
++  { { echo "$as_me:$LINENO: warning: cannot run test program while cross compiling
  See \`config.log' for more details." >&5
--echo "$as_me: error: C compiler cannot create executables
-+echo "$as_me: warning: C compiler cannot create executables
+-echo "$as_me: error: cannot run test program while cross compiling
++echo "$as_me: warning: cannot run test program while cross compiling
  See \`config.log' for more details." >&2;}
--   { (exit 77); exit 77; }; }
-+    }
- fi
- 
- ac_exeext=$ac_cv_exeext
+-   { (exit 1); exit 1; }; }
++ }
+ else
+   cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
